### ISSUE TITLE
Convert .xplt to vtk in Multiphasic Analysis

### ISSUE THREAD

**Issue by steffenger** [febiosoftware/FEBioStudio#48]
Hello FEBio,

I simulated a Multiphasic Analysis with two solutes and I tried to convert the results to the vtk format.
It seems that the vtk export function does not work properly, because not all data fields are exported (For example solute concentration).
 If I have made a mistake or missed something in the data fields or if you need more information, please let me know.

best regards,

steffen

[benchmark_lobule.zip](https://github.com/febiosoftware/FEBioStudio/files/8471330/benchmark_lobule.zip)
[benchmark_lobule.t10.zip](https://github.com/febiosoftware/FEBioStudio/files/8471349/benchmark_lobule.t10.zip)

**Comment by SteveMaas1978** [comment]
Hi Steffen,

The VTK export feature only exports the data variable that is currently plotted. It does not output all variables. I can look into adding an option to support this if that would be helpful.

Best,

Steve

**Comment by steffenger** [comment]
Hi Steve,

What do you mean with "currently plotted"? Since all the variables are specified in the input file. 

`<Output>
		<plotfile type="febio">
			<var type="displacement"/>
			<var type="stress"/>
			<var type="effective fluid pressure"/>
			<var type="fluid flux"/>
			<var type="solid stress"/>
			<var type="effective solute concentration"/>
			<var type="solute concentration"/>
			<var type="solute flux"/>
		</plotfile>
	</Output>`

And for example, the displacement is successfully exported to vtk but others are not. Maybe there are differences how the variables are defined in the sorce code?

Best regards,

Steffen

**Comment by SteveMaas1978** [comment]
Hi Steffen,

Ignore what I said before. I was thinking of another file export format. 

The reason why the concentration is not output, is because this is an array variable and these variables are currently not exported to VTK (only scalar, vector, and tensors are supported). I'll see if I can find a way to export these types of variables to the VTK file as well.

Best,

Steve

**Comment by steffenger** [comment]
Hi Steve,

is there an update on this situation?

Best regards,

Steffen

**Comment by SteveMaas1978** [comment]
Hi Steffen,

I committed a fix to the develop version yesterday that address some (though not all) of the limitations of vtk export. In particular, array variables are now exported to a FIELD data set in the vtk file. Please update to the [dev version](https://febio.org/knowledgebase/getting-started/updating-febio-and-febio-studio/) and give it a try. Let me know what you find. 

Thanks,

Steve

**Comment by steffenger** [comment]
Hi Steve, 

I did the update to 1.9.0 via the tools panel. But when i export to vtk, the issue with my application is still the same, that there are no concentrations in the vtk files.

.xplt file

![image](https://user-images.githubusercontent.com/95339856/231747017-75799eb5-731d-4f22-961f-6dea220425ae.png)

vtk file

![image](https://user-images.githubusercontent.com/95339856/231747331-0301fe64-d41e-4adb-8875-29c46b74a876.png)

Or did i something wrong?

best regards,

Steffen

**Comment by SteveMaas1978** [comment]
Hi Steffen,

I implemented the fix in the 2.1 version. Can you try upgrading to that version and then give it a try?

Thanks,

Steve

**Comment by steffenger** [comment]
Hi Steve,

I tried Version 2.1.1 from https://febio.org/downloads/ but the vtk still looks the same:D Is this the right version?

Best regards,

Steffen

**Comment by SteveMaas1978** [comment]
Hi Steffen,

This fix was implemented in the develop version. After you install the 2.1.1 version, follow [these ](https://febio.org/knowledgebase/getting-started/updating-febio-and-febio-studio/)instructions to update to the latest development version. 

Best,

Steve
